name: Build GreenSurf Portable EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build Portable EXE
        run: npm run dist

      - name: Upload EXE Artifact
        uses: actions/upload-artifact@v4
        with:
          name: GreenSurfPortable
          path: dist/*.exe
